[theme]
primaryColor             = "#F97316"
backgroundColor          = "#080D1A"
secondaryBackgroundColor = "#0F172A"
textColor                = "#F1F5F9"
font                     = "sans serif"

[server]
headless = true
